CREATE TABLE Movies (
	title VARCHAR(50), 
	year INT, 
 	length INT, 
	genre VARCHAR(50) );
INSERT INTO Movies (title, year, genre, length) VALUES ("The Wizard of Oz", 1925, "comedy", 81);
INSERT INTO Movies (title, year, genre, length) VALUES ("Frankenstein", 1931, "drama", 70);
INSERT INTO Movies (title, year, genre, length) VALUES ("King Kong", 1933, "adventure", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Invisible Man", 1933, "horror", 71);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Adventures of Robin Hood", 1938, "action", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Wizard of Oz", 1939, "musical", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Great Dictator", 1940, "comedy", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Casablanca", 1942, "drama", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("Singin' in the Rain", 1952, "comedy", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("Rebel Without a Cause", 1955, "drama", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Breakfast at Tiffany's", 1961, "comedy", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dr. No", 1962, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("To Kill a Mockingbird", 1962, "crime", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Whatever Happened To Baby Jane?", 1962, "drama", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("From Russia with Love", 1963, "action", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Goldfinger", 1964, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Sound of Music", 1965, "biography", 172);
INSERT INTO Movies (title, year, genre, length) VALUES ("Thunderball", 1965, "action", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Good, the Bad and the Ugly", 1966, "western", 161);
INSERT INTO Movies (title, year, genre, length) VALUES ("You Only Live Twice", 1967, "action", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Diamonds Are Forever", 1971, "action", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Cabaret", 1972, "drama", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Deliverance", 1972, "adventure", 109);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Godfather", 1972, "action", 177);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Poseidon Adventure", 1972, "action", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("La Patagonia rebelde", 1974, "historical", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Godfather: Part II", 1974, "action", 200);
INSERT INTO Movies (title, year, genre, length) VALUES ("Monty Python and the Holy Grail", 1975, "adventure", 91);
INSERT INTO Movies (title, year, genre, length) VALUES ("One Flew Over the Cuckoo's Nest", 1975, "comedy", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("Eraserhead", 1977, "horror", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode IV - A New Hope", 1977, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Piranha", 1978, "horror", 95);
INSERT INTO Movies (title, year, genre, length) VALUES ("Superman", 1978, "action", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("Alien", 1979, "horror", 116);
INSERT INTO Movies (title, year, genre, length) VALUES ("Life of Brian", 1979, "comedy", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mad Max", 1979, "action", 93);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode V - The Empire Strikes Back", 1980, "action", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Blue Lagoon", 1980, "romance", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("Indiana Jones: Raiders of the Lost Ark", 1981, "action", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mad Max 2: The Road Warrior", 1981, "action", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Superman II", 1981, "action", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("Blade Runner", 1982, "sci-fi", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Never Say Never Again", 1983, "action", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode VI - Return of the Jedi", 1983, "action", 131);
INSERT INTO Movies (title, year, genre, length) VALUES ("Superman III", 1983, "action", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Meaning of Life", 1983, "comedy", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Indiana Jones and the Temple of Doom", 1984, "action", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Nausicaa of the Valley of the Wind", 1984, "fantasy", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Purple Rain", 1984, "rock musical", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Terminator", 1984, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("After Hours", 1985, "comedy", 97);
INSERT INTO Movies (title, year, genre, length) VALUES ("Back to the Future", 1985, "comedy", 116);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mad Max 3: Beyond Thunderdome", 1985, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Breakfast Club", 1985, "comedy", 97);
INSERT INTO Movies (title, year, genre, length) VALUES ("Labyrinth", 1986, "action", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Top Gun", 1986, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spaceballs", 1987, "adventure", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Superman IV: The Quest For Peace", 1987, "action", 90);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Princess Bride", 1987, "adventure", 98);
INSERT INTO Movies (title, year, genre, length) VALUES ("Akira", 1988, "animation", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("They Live", 1988, "action", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dead Poets Society", 1989, "drama", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("Glory", 1989, "biography", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Indiana Jones and the Last Crusade", 1989, "action", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Punisher", 1989, "action", 89);
INSERT INTO Movies (title, year, genre, length) VALUES ("Edward Scissorhands ", 1990, "drama", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("Home Alone", 1990, "comedy", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Godfather: Part III", 1990, "action", 162);
INSERT INTO Movies (title, year, genre, length) VALUES ("An American Tail: Fievel Goes West", 1991, "comedy", 74);
INSERT INTO Movies (title, year, genre, length) VALUES ("Backdraft", 1991, "action", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("Manta, Manta", 1991, "comedy", 91);
INSERT INTO Movies (title, year, genre, length) VALUES ("My Girl", 1991, "comedy", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("Point Break", 1991, "action", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Terminator 2: Judgment Day", 1991, "action", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Silence of the Lambs", 1991, "crime", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Death Becomes Her", 1992, "comedy", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Home Alone 2: Lost in New York", 1992, "comedy", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Lorenzo's Oil", 1992, "drama", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dragon: The Bruce Lee Story", 1993, "biography", 1120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jurassic Park", 1993, "adventure", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dumb and Dumber", 1994, "adventure", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Forrest Gump", 1994, "drama", 142);
INSERT INTO Movies (title, year, genre, length) VALUES ("Little Giants", 1994, "comedy", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pulp Fiction", 1994, "detective", 178);
INSERT INTO Movies (title, year, genre, length) VALUES ("Schindlers List", 1994, "biography", 195);
INSERT INTO Movies (title, year, genre, length) VALUES ("Street Fighter", 1994, "action", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lion King", 1994, "animated", 88);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Mask", 1994, "comedy", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Shawshank Redemption", 1994, "crime", 142);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ghost in the Shell", 1995, "animation", 85);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hackers", 1995, "comedy", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jumanji", 1995, "adventure", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kicking and Screaming", 1995, "comedy", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Happy Gilmore", 1996, "comedy", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Independence Day", 1996, "action", 145);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission: Impossible", 1996, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Space Jam", 1996, "animation", 88);
INSERT INTO Movies (title, year, genre, length) VALUES ("Twister", 1996, "action", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Starship Troopers", 1997, "action", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Fifth Element", 1997, "action", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lost World: Jurassic Park", 1997, "adventure", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Armageddon", 1998, "action", 151);
INSERT INTO Movies (title, year, genre, length) VALUES ("American Beauty", 1999, "drama", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fight Club", 1999, "drama", 139);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pretty Woman", 1999, "comedy", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode I - The Phantom Menace", 1999, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Matrix", 1999, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Sixth Sense", 1999, "horror", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Crouching Tiger, Hidden Dragon", 2000, "wuxia", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dude, Where's My Car?", 2000, "comedy", 83);
INSERT INTO Movies (title, year, genre, length) VALUES ("Finding Forrester", 2000, "drama", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Gladiator", 2000, "adventure", 155);
INSERT INTO Movies (title, year, genre, length) VALUES ("High Fidelity", 2000, "comedy", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission: Impossible II", 2000, "action", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("Remember the Titans", 2000, "biography", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Replacements", 2000, "comedy", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men", 2000, "action", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("A Beautiful Mind", 2001, "drama", 135);
INSERT INTO Movies (title, year, genre, length) VALUES ("A.I. Artificial Intelligence", 2001, "drama", 146);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hard Ball", 2001, "drama", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Sorcerer's Stone", 2001, "adventure", 152);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jay and Silent Bob Strike Back", 2001, "comedy", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Memento", 2001, "thriller", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ocean's Eleven", 2001, "thriller", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spirited Away", 2001, "adventure", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Fast and the Furious", 2001, "action", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lord of the Rings: The Fellowship of the Ring", 2001, "action", 178);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lost World: Jurassic Park", 2001, "adventure", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("28 Days Later", 2002, "drama", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Chamber of Secrets", 2002, "adventure", 161);
INSERT INTO Movies (title, year, genre, length) VALUES ("Reign of Fire", 2002, "action", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil", 2002, "horror", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spiderman", 2002, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode II - Attack of the Clones", 2002, "action", 142);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Bourne Identity", 2002, "action", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lord of the Rings: The Two Towers", 2002, "action", 179);
INSERT INTO Movies (title, year, genre, length) VALUES ("2 Fast 2 Furious", 2003, "action", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("Daredevil", 2003, "action", 10);
INSERT INTO Movies (title, year, genre, length) VALUES ("Finding Nemo", 2003, "animation", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kill Bill Volume 1", 2003, "action", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Oldboy", 2003, "action", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spring, Summer, Fall, Winter and Spring", 2003, "drama", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("Terminator 3: Rise of the Machines", 2003, "action", 109);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lord of the Rings: The Return of the King", 2003, "action", 201);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Matrix Reloaded", 2003, "sci-fi", 138);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Matrix Revolutions", 2003, "action", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Room", 2003, "drama", 99);
INSERT INTO Movies (title, year, genre, length) VALUES ("Underworld", 2003, "horror", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men 2", 2003, "action", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("50 First Dates", 2004, "comedy", 99);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Prisoner of Azkaban", 2004, "adventure", 142);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil 2: Apocalypse", 2004, "horror", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("Secret Window", 2004, "drama", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spiderman 2", 2004, "action", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Notebook", 2004, "drama", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Phantom of the Opera", 2004, "drama", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Punisher", 2004, "action", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("King Kong", 2005, "drama", 187);
INSERT INTO Movies (title, year, genre, length) VALUES ("Batman Begins", 2005, "adventure", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("Coach Carter", 2005, "biographical", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Constantine", 2005, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Goblet of Fire", 2005, "adventure", 157);
INSERT INTO Movies (title, year, genre, length) VALUES ("Lord of War", 2005, "chrime", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mr. & Mrs. Smith", 2005, "action", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pride & Prejudice", 2005, "drama", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode III - Revenge of the Sith", 2005, "action", 140);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hitchhiker's Guide to the Galaxy", 2005, "adventure", 109);
INSERT INTO Movies (title, year, genre, length) VALUES ("V for Vendetta", 2005, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Walk the Line", 2005, "biography", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Casino Royale", 2006, "action", 144);
INSERT INTO Movies (title, year, genre, length) VALUES ("Eragon", 2006, "action", 154);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission Impossible III", 2006, "action", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Superman Returns", 2006, "action", 154);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Fast and the Furious: Tokyo Drift", 2006, "action", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Prestige", 2006, "thriller", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Pursuit of Happyness", 2006, "biography", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Underworld: Evolution", 2006, "horror", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men: The Last Stand", 2006, "action", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("American Drug War: The Last White Hope", 2007, "documentary", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fantastic 4: Rise of the Silver Surfer", 2007, "action", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fool & Final", 2007, "indian", 160);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Order of the Phoenix", 2007, "adventure", 138);
INSERT INTO Movies (title, year, genre, length) VALUES ("Juno", 2007, "comedy", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil 3: Extinction", 2007, "horror", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spiderman 3", 2007, "action", 139);
INSERT INTO Movies (title, year, genre, length) VALUES ("Sunshine", 2007, "thriller", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Transformers", 2007, "action", 144);
INSERT INTO Movies (title, year, genre, length) VALUES ("Iron Man", 2008, "adventure", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kung Fu Panda", 2008, "animation", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Punisher: War Zone", 2008, "action", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("Quantum of Solace", 2008, "action", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Book", 2008, "short", 11);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Dark Knight", 2008, "adventure", 152);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Incredible Hulk", 2008, "action", 112);
INSERT INTO Movies (title, year, genre, length) VALUES ("Exam", 2009, "mystery", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fast & Furious", 2009, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("G.I. Joe: The Rise of Cobra", 2009, "adventure", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hachi: A Dog's Tale", 2009, "drama", 93);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Half-Blood Prince", 2009, "adventure", 153);
INSERT INTO Movies (title, year, genre, length) VALUES ("Orphan", 2009, "horror", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("Sherlock Holmes", 2009, "action", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Trek", 2009, "action", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("Terminator Salvation", 2009, "action", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Transformers: Revenge of the Fallen", 2009, "action", 150);
INSERT INTO Movies (title, year, genre, length) VALUES ("Underworld: Rise of the Lycans", 2009, "horror", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Watchmen", 2009, "action", 215);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men Origins: Wolverine", 2009, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Due Date", 2010, "comedy", 95);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Deathly Hallows: Part 1", 2010, "adventure", 146);
INSERT INTO Movies (title, year, genre, length) VALUES ("How To Train Your Dragon", 2010, "animation", 98);
INSERT INTO Movies (title, year, genre, length) VALUES ("Inception", 2010, "adventure", 148);
INSERT INTO Movies (title, year, genre, length) VALUES ("Iron Man 2", 2010, "adventure", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Percy Jackson and the Olympians: The Lightning Thief", 2010, "adventure", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Red", 2010, "comedy", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil 4: Afterlife", 2010, "horror", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Book of Eli", 2010, "adventure", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Social Network", 2010, "biography", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Tourist", 2010, "action", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("Captain America: The First Avenger", 2011, "adventure", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fast Five", 2011, "action", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Harry Potter and the Deathly Hallows: Part 2", 2011, "adventure", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kung Fu Panda 2", 2011, "animation", 90);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission Impossible - Ghost Protocol", 2011, "action", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Sherlock Holmes: A Game of Shadows", 2011, "action", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Rite", 2011, "drama", 114);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Rum diary", 2011, "comedy", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Thor", 2011, "adventure", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Transformers: Dark of the Moon", 2011, "action", 154);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men: First Class", 2011, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Django Unchained", 2012, "drama", 165);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jack Reacher", 2012, "action", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil 5: Retribution", 2012, "horror", 95);
INSERT INTO Movies (title, year, genre, length) VALUES ("Skyfall", 2012, "action", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Avengers", 2012, "action", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Dark Knight Rises", 2012, "adventure", 164);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Help", 2012, "drama", 146);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hobbit: An Unexpected Journey", 2012, "adventure", 169);
INSERT INTO Movies (title, year, genre, length) VALUES ("Underworld: Awakening", 2012, "horror", 88);
INSERT INTO Movies (title, year, genre, length) VALUES ("Coherence", 2013, "mystery", 89);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fast & Furious 6", 2013, "action", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Frozen", 2013, "animation", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("G.I. Joe: Retaliation", 2013, "adventure", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Her", 2013, "drama", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Iron Man 3", 2013, "adventure", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Man of Steel", 2013, "action", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("Oldboy", 2013, "action", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pacific Rim", 2013, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Percy Jackson: Sea of Monsters", 2013, "adventure", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Rubinrot", 2013, "drama", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Rush", 2013, "drama", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Trek Into Darkness", 2013, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hobbit: The Desolation of Smaug", 2013, "adventure", 161);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Secret Life of Walter Mitty", 2013, "adventure", 114);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Wolverine", 2013, "action", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Thor: The Dark World", 2013, "adventure", 112);
INSERT INTO Movies (title, year, genre, length) VALUES ("Back Country", 2014, "drama", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Big Hero 6", 2014, "animation", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Captain America: The Winter Soldier", 2014, "adventure", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dracula Untold", 2014, "action", 92);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dukhtar", 2014, "drama", 93);
INSERT INTO Movies (title, year, genre, length) VALUES ("Gone Girl", 2014, "mystery", 149);
INSERT INTO Movies (title, year, genre, length) VALUES ("Guardians of the Galaxy", 2014, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("How To Train Your Dragon 2", 2014, "animation", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("Interstellar", 2014, "adventure", 169);
INSERT INTO Movies (title, year, genre, length) VALUES ("John Wick", 2014, "action", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kingsman: The Secret Service", 2014, "adventure", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Lucy", 2014, "action", 89);
INSERT INTO Movies (title, year, genre, length) VALUES ("Predestination", 2014, "thriller", 97);
INSERT INTO Movies (title, year, genre, length) VALUES ("Road to Paloma", 2014, "drama", 91);
INSERT INTO Movies (title, year, genre, length) VALUES ("Saphirblau", 2014, "drama", 116);
INSERT INTO Movies (title, year, genre, length) VALUES ("That Awkward Moment", 2014, "comedy", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hobbit: The Battle of the Five Armies", 2014, "adventure", 144);
INSERT INTO Movies (title, year, genre, length) VALUES ("Transformers: Age of Extinction", 2014, "action", 165);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men: Days of Future Past", 2014, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ant-Man", 2015, "action", 117);
INSERT INTO Movies (title, year, genre, length) VALUES ("Capitao Falcao", 2015, "action", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Furious 7", 2015, "action", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("Inside Out", 2015, "animation", 94);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jurassic World", 2015, "adventure", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kung Fury", 2015, "fantasy", 31);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mad Max 4: Fury Road", 2015, "action", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission Impossible - Rogue Nation", 2015, "action", 131);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mortdecai", 2015, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spectre", 2015, "action", 148);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode 7 - The Force Awakens", 2015, "action", 138);
INSERT INTO Movies (title, year, genre, length) VALUES ("Terminator Genisys", 2015, "action", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hateful Eight", 2015, "crime", 187);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Martian", 2015, "sci-fi", 151);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ah-ga-ssi", 2016, "drama", 145);
INSERT INTO Movies (title, year, genre, length) VALUES ("Allied", 2016, "adventure", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Aquarius", 2016, "drama", 165);
INSERT INTO Movies (title, year, genre, length) VALUES ("Arrival", 2016, "mystery", 116);
INSERT INTO Movies (title, year, genre, length) VALUES ("Batman v Superman: Dawn of Justice", 2016, "action", 151);
INSERT INTO Movies (title, year, genre, length) VALUES ("Captain America: Civil War", 2016, "adventure", 147);
INSERT INTO Movies (title, year, genre, length) VALUES ("Criminal", 2016, "mistery", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Deadpool", 2016, "action", 108);
INSERT INTO Movies (title, year, genre, length) VALUES ("Doctor Strange", 2016, "action", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fantastic Beasts and Where to Find Them", 2016, "adventure", 133);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hacksaw Ridge", 2016, "biographical drama", 139);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hunt For The Wilderpeople", 2016, "drama", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jason Bourne", 2016, "action", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kingsglaive: Final Fantasy XV", 2016, "adventure", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kung Fu Panda 3", 2016, "animation", 95);
INSERT INTO Movies (title, year, genre, length) VALUES ("La La Land", 2016, "romance", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("Me Before You", 2016, "drama", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Moana", 2016, "animation", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Moonlight", 2016, "drama", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Passengers", 2016, "drama", 116);
INSERT INTO Movies (title, year, genre, length) VALUES ("Resident Evil 6: The final chapter", 2016, "horror", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Rogue One: A Star Wars Story", 2016, "action", 133);
INSERT INTO Movies (title, year, genre, length) VALUES ("Smaragdgrün", 2016, "fantasy", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Trek Beyond", 2016, "action", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Suicide Squad", 2016, "sci-fi", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Accountant", 2016, "action", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Conjuring 2", 2016, "mystery", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Legend of Tarzan", 2016, "drama", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Magnificent Seven", 2016, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Void", 2016, "horror", 90);
INSERT INTO Movies (title, year, genre, length) VALUES ("Underworld: Blood Wars", 2016, "action", 91);
INSERT INTO Movies (title, year, genre, length) VALUES ("Warcraft", 2016, "action", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("X-Men: Apocalypse", 2016, "action", 144);
INSERT INTO Movies (title, year, genre, length) VALUES ("Your Lie in April", 2016, "teen-fantasy", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Zootopia", 2016, "animation", 108);
INSERT INTO Movies (title, year, genre, length) VALUES ("A Dog's Purpose", 2017, "drama", 135);
INSERT INTO Movies (title, year, genre, length) VALUES ("Annabelle: Creation", 2017, "horror", 109);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ayla: The Daughter of War", 2017, "drama", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Baahubali 2: The Conclusion", 2017, "fantasy", 197);
INSERT INTO Movies (title, year, genre, length) VALUES ("Baby Driver", 2017, "action", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("Beauty and the Beast", 2017, "family", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Detective Conan Movie 21: Karakurenai no Love Letter", 2017, "action", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dunkirk", 2017, "action", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Get Out", 2017, "horror", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ghost in the Shell", 2017, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Guardians of the Galaxy Vol. 2", 2017, "action", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("Happy Death Day", 2017, "horror", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("It", 2017, "drama", 135);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jumanji: Welcome to the jungle", 2017, "adventure", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Justice League", 2017, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kimi No Na Wa (Your Name)", 2017, "animation", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Kingsman: The Golden Circle", 2017, "adventure", 141);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pitch Perfect 3", 2017, "comedy", 93);
INSERT INTO Movies (title, year, genre, length) VALUES ("Raees", 2017, "thriller", 161);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spiderman Homecoming", 2017, "action", 133);
INSERT INTO Movies (title, year, genre, length) VALUES ("Star Wars: Episode 8 - The Last Jedi", 2017, "action", 150);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Dark Tower", 2017, "sci-fi", 95);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Disaster Artist", 2017, "biography", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Fate of the Furious", 2017, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Greatest Showman", 2017, "biography", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Invisible Man", 2017, "sci-fi", 88);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Mummy", 2017, "action", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Shape of Water", 2017, "adventure", 123);
INSERT INTO Movies (title, year, genre, length) VALUES ("Thor: Ragnarok", 2017, "action", 137);
INSERT INTO Movies (title, year, genre, length) VALUES ("War of The Planet Of The Apes", 2017, "action", 140);
INSERT INTO Movies (title, year, genre, length) VALUES ("Wonder Woman", 2017, "fantasy", 141);
INSERT INTO Movies (title, year, genre, length) VALUES ("Truth or Dare", 2018, "horror", 103);
INSERT INTO Movies (title, year, genre, length) VALUES ("A Quiet Place", 2018, "drama", 91);
INSERT INTO Movies (title, year, genre, length) VALUES ("A Star is Born", 2018, "drama", 135);
INSERT INTO Movies (title, year, genre, length) VALUES ("Acrimony", 2018, "drama", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Annihilation", 2018, "adventure", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ant-Man and the Wasp", 2018, "action", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Aquaman", 2018, "fantasy", 140);
INSERT INTO Movies (title, year, genre, length) VALUES ("Arif v 216", 2018, "comedy", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Avengers: Infinity War", 2018, "action", 149);
INSERT INTO Movies (title, year, genre, length) VALUES ("Beautiful Boy", 2018, "biography", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Bigger", 2018, "drama", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Black Panther", 2018, "action", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("Bohemian Rhapsody", 2018, "biography", 134);
INSERT INTO Movies (title, year, genre, length) VALUES ("Bumblebee", 2018, "action", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Christopher Robin", 2018, "animation", 104);
INSERT INTO Movies (title, year, genre, length) VALUES ("Crazy Rich Asians", 2018, "comedy-drama", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Das schönste Mädchen der Welt", 2018, "comedy", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("Deadpool 2", 2018, "action", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("El Ángel", 2018, "drama", 126);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fifty Shades Freed", 2018, "drama", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("First Man", 2018, "biography", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Goosebumps 2: Haunted Halloween", 2018, "adventure", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("Halloween", 2018, "horror", 109);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hereditary", 2018, "drama", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hold the Dark", 2018, "drama", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Incredibles 2", 2018, "animation", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Isle of Dogs", 2018, "animation", 101);
INSERT INTO Movies (title, year, genre, length) VALUES ("Johnny English Strikes Again", 2018, "action", 88);
INSERT INTO Movies (title, year, genre, length) VALUES ("Jurassic World: Fallen Kingdom", 2018, "action", 130);
INSERT INTO Movies (title, year, genre, length) VALUES ("Love, Simon", 2018, "comedy", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mary Poppins Returns", 2018, "family", 145);
INSERT INTO Movies (title, year, genre, length) VALUES ("Maze Runner: The Death Cure", 2018, "action", 143);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mid90s", 2018, "comedy", 84);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mission: Impossible - Fallout", 2018, "action", 148);
INSERT INTO Movies (title, year, genre, length) VALUES ("Mortal Engines", 2018, "fantasy", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ocean's 8", 2018, "comedy", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pacific Rim: Uprising", 2018, "action", 111);
INSERT INTO Movies (title, year, genre, length) VALUES ("Paul, Apostle of Christ", 2018, "biblic", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Petta", 2018, "action", 120);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ralph Breaks the Internet", 2018, "animation", 142);
INSERT INTO Movies (title, year, genre, length) VALUES ("Rampage", 2018, "action", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ready Player One", 2018, "action", 140);
INSERT INTO Movies (title, year, genre, length) VALUES ("Searching", 2018, "drama", 112);
INSERT INTO Movies (title, year, genre, length) VALUES ("Skyscraper", 2018, "horror", 102);
INSERT INTO Movies (title, year, genre, length) VALUES ("Smallfoot", 2018, "animation", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("Solo: A Star Wars Story", 2018, "action", 135);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Happy Prince", 2018, "history", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Hate U Give", 2018, "crime", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("The House with a Clock in Its Walls", 2018, "comedy", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Kindergarten Teacher", 2018, "drama", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Meg", 2018, "action", 113);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Nun", 2018, "horror", 96);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Predator", 2018, "horror", 107);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Strangers: Prey at Night", 2018, "horror", 85);
INSERT INTO Movies (title, year, genre, length) VALUES ("To All the Boys I've Loved Before", 2018, "drama", 99);
INSERT INTO Movies (title, year, genre, length) VALUES ("Tomb Raider", 2018, "action", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("Upgrade", 2018, "horror", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("Venom", 2018, "horror", 112);
INSERT INTO Movies (title, year, genre, length) VALUES ("Vice", 2018, "biography", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Winchester", 2018, "biography", 99);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ad Astra", 2019, "adventure", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("After", 2019, "drama", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("Aladdin", 2019, "adventure", 128);
INSERT INTO Movies (title, year, genre, length) VALUES ("Angel Has Fallen", 2019, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Annabelle Comes Home", 2019, "supernatural", 106);
INSERT INTO Movies (title, year, genre, length) VALUES ("Avengers: Endgame", 2019, "action", 181);
INSERT INTO Movies (title, year, genre, length) VALUES ("Bacurau", 2019, "drama", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Captain Marvel", 2019, "action", 125);
INSERT INTO Movies (title, year, genre, length) VALUES ("Dark Phoenix", 2019, "action", 114);
INSERT INTO Movies (title, year, genre, length) VALUES ("Fast & Furious Presents: Hobbs & Shaw", 2019, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Glass", 2019, "drama", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("Godzilla: King of the Monsters", 2019, "action", 132);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hellboy", 2019, "action", 121);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hobbs & Shaw", 2019, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hobbs & Shaw", 2019, "action", 136);
INSERT INTO Movies (title, year, genre, length) VALUES ("Hustlers", 2019, "comedy", 110);
INSERT INTO Movies (title, year, genre, length) VALUES ("Ich war noch niemals in New York", 2019, "comedy", 127);
INSERT INTO Movies (title, year, genre, length) VALUES ("John Wick Parabellum", 2019, "action", 131);
INSERT INTO Movies (title, year, genre, length) VALUES ("Joker", 2019, "crime", 122);
INSERT INTO Movies (title, year, genre, length) VALUES ("Lucy in The Sky", 2019, "drama", 124);
INSERT INTO Movies (title, year, genre, length) VALUES ("Maleficent Mistress of Evil", 2019, "fantasy", 119);
INSERT INTO Movies (title, year, genre, length) VALUES ("Men in Black: International", 2019, "action", 115);
INSERT INTO Movies (title, year, genre, length) VALUES ("Pokémon Detective Pikachu", 2019, "action", 105);
INSERT INTO Movies (title, year, genre, length) VALUES ("Spider-Man: Far from Home", 2019, "action", 129);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Curse of La Llorona", 2019, "horror", 93);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Lion King", 2019, "animation", 118);
INSERT INTO Movies (title, year, genre, length) VALUES ("The Secret Life of Pets 2", 2019, "animation", 86);
INSERT INTO Movies (title, year, genre, length) VALUES ("Toy Story 4", 2019, "animation", 100);
INSERT INTO Movies (title, year, genre, length) VALUES ("Us", 2019, "horror", 116);
