# If you don't like the Mets (?) you can
# change this...
team = "Mets"

# Make sure you type python3 on your
# command line when running this...
# otherwise you'll get an odd printout...
print ("Lets go", team, "!")

